wordpress-mobile/WordPress-iOS-Shared

WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.h
WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.m

`WPTableViewSectionFooterView` fixed width support added similar to how it works in `WPTableViewSectionHeaderView`. Closes #49.

WPTableViewSectionFooterView fixed width support added

---

WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.h
WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.m
WordPress-iOS-Shared/Core/WPTableViewSectionHeaderView.h
WordPress-iOS-Shared/Core/WPTableViewSectionHeaderView.m

There were a few different problems with how we calculated the width and height of the header and footer. I've updated these calculations completely. This is not a perfect solution, although it's a big step up from the previous version. In the future, it would be good to at least remove the duplication of code between footer and header, but as a hotfix this should do for now. With this fix, there should be no overlap between the section header and section content in case the header is multiline.
@aerych & @jleandroperez Can I bother you guys with a quick review?

Fix header and footer width/height calculation

---

WordPress-iOS-Shared-Example/WordPress-iOS-Shared-Example/DeviceTableViewController.m

Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Shared/issues/58).
/cc @SergioEstevao

Fixes the title of the device identification VC.

---

Podfile
Podfile.lock
WordPress-iOS-Shared.xcodeproj/project.pbxproj
WordPress-iOS-Shared/Core/WPAnimatedImageResponseSerializer.h
WordPress-iOS-Shared/Core/WPAnimatedImageResponseSerializer.m

Fixes #62 
Updates an import statement for an AFNetworking framework header so that other pods using this one will pass validation.

Use proper import statement syntax for frameworks

---

Podfile
Podfile.lock
WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared-Example/WordPress-iOS-Shared-Example/ColorsTableViewController.m
WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/Core/WPFontManager.m
WordPress-iOS-Shared/Core/WPImageSource.m
WordPress-iOS-Shared/WordPress-iOS-Shared-Prefix.pch
WordPress-iOS-SharedTests/AsyncTestHelper.m

Closes #64 
This will help with updating to CocoaPods 0.36 and Xcode 6.3 on the subpods. We no longer have to define _ddLogLevel which is a HUGE help with libraries.

Update to CocoaLumberjack 2.0 

---

WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.m

In this PR we're simply updating **WPTableSectionFooterView**'s default style. Inconsistencies will be addressed in the main WPiOS's repository.
Needs Review: @aerych (thanks in advance Eric!)

Updates TableSectionFooter Style

---

WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.h
WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.m

We'll expose the Title Alignment, which is required to wrap up [this WPiOS Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3998)
Needs Review: @diegoreymendez

WPTableViewSectionFooter: Adds Title Alignment Property

---

WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/Core/WPTableViewSectionFooterView.m

We were using a different font for the Height calculation. In this PR we're simply normalizing both fonts, and updating the Podspec as well.
Needs Review: @diegoreymendez (Thank you Diego!)

Fixes WPTableViewSectionFooterView height calculation

---

.travis.yml

This seems to get us cocoapods 0.39 and fixes the build errors
Needs Review: @jleandroperez

Update Travis Xcode version

---

WordPress-iOS-Shared/Core/WPStyleGuide.h
WordPress-iOS-Shared/Core/WPStyleGuide.m
WordPress-iOS-Shared/Core/WPTableViewSectionHeaderFooterView.h

WPTableViewSectionHeaderFooterView started its life as a way to customize the section headers to adapt to iOS 7 design changes, and has grown into a different beast today.
Of all the things it does, we just care about using a custom font and color, which can be achieved without custom classes, using the delegate method `tableView:willDisplayHeaderView:forSection:`.
I've marked WPTableViewSectionHeaderFooterView as deprecated and it should be removed in a next version once everything is migrated.
I've also added a couple new methods to call on `tableView:willDisplayHeaderView:forSection:` and `tableView:willDisplayFooterView:forSection:`.
For example usage see https://github.com/wordpress-mobile/WordPress-iOS/pull/4591

Deprecate WPTableViewSectionHeaderFooterView

---

WordPress-iOS-Shared/Core/WPStyleGuide.h
WordPress-iOS-Shared/Core/WPStyleGuide.m
WordPress-iOS-Shared/Core/WPTableViewSectionHeaderFooterView.h

Reverts wordpress-mobile/WordPress-Shared-iOS#85
In https://github.com/wordpress-mobile/WordPress-iOS/pull/4591we decided not to go forward until we can get rid of `WPTableViewCell`

Revert "Deprecate WPTableViewSectionHeaderFooterView"

---

WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared/Core/WPStyleGuide.m

Closes #88 
Adds a default 10% lightened grey to all image views in table view cells.
Needs Review: @jleandroperez

Add tint color to table view cell image views

---

.travis.yml
Podfile
WordPress-iOS-Shared-Example/Podfile
WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared-Example/WordPress-iOS-Shared-Example.xcodeproj/project.pbxproj
WordPress-iOS-Shared.podspec
WordPress-iOS-Shared.xcodeproj/project.pbxproj
WordPress-iOS-Shared.xcodeproj/xcshareddata/xcschemes/WordPressShared.xcscheme
WordPress-iOS-Shared/Core/WPDeviceIdentification.h
WordPress-iOS-Shared/Core/WPDeviceIdentification.m
WordPress-iOS-Shared/Core/WPImageSource.h
WordPress-iOS-Shared/Core/WPNoResultsView.m
WordPress-iOS-Shared/Core/WPStyleGuide.m
WordPress-iOS-Shared/Core/WPTableViewCell.m
WordPress-iOS-Shared/Core/WPTableViewSectionHeaderFooterView.m
WordPress-iOS-Shared/Core/WPTextFieldTableViewCell.m
WordPress-iOS-Shared/WordPress-iOS-Shared-Prefix.pch
WordPress-iOS-SharedTests/UIColorHelpersTests.swift
WordPress-iOS-SharedTests/WordPress-iOS-SharedTests-Bridging-Header.h
WordPressShared/Info.plist
WordPressShared/WordPressShared.h

So far the project was building a static library. There are plenty of reasons to switch to frameworks but what triggered this was trying to add Swift code and Swift unit tests.
This PR:
- Adds a new `WordPressShared` framework target/scheme
- Bumps the iOS deployment target to 8.0, since it's the minimum that supports frameworks
- Switch the unit tests to use the framework instead of the static library
- Adds a small unit test in Swift to verify that it's working
- Removed `IS_IPAD` and other macros from the PCH file and converted them to regular methods in `WPDeviceIdentification`
- Switch travis to build the new scheme with xcodebuild, as that's what we're using everywhere else.
Needs Review: @SergioEstevao

Add WordPressShared framework target

---

WordPress-iOS-Shared/Core/WPTableViewSectionHeaderFooterView.h
WordPress-iOS-Shared/Core/WPTableViewSectionHeaderFooterView.m

This PR adds an `attributedTitle` property to `WPTableViewSectionHeaderFooterView`, so that the text can have extra styles applied to it. 
This will initially be used to a create tappable-looking footer in the Plans section of WPiOS:
To test:
* Check out the `feature/plans-tos-link` branch of WPiOS
* Map all references to `WordPress-iOS-Shared` in the `Podfile` to use this branch: `pod 'WordPress-iOS-Shared', :git => 'https://github.com/wordpress-mobile/WordPress-Shared-iOS.git', :branch => 'feature/attributed-header-footer-view'`
* Build and run WPiOS, navigate into a .com site, choose Plans, and view the footer at the bottom of the list.
Needs review: @jleandroperez 
Thanks!

WPTableViewSectionHeaderFooterView: Added attributed title.

---

WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared/Core/WPNoResultsView.m

Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/5293), which is caused by the code not enforcing some GUI layout rules in the appropriate spots.
If the fix is accepted a follow-up PR will boost the pod version and properly include it in WPiOS.
1. Checkout WPiOS branch `issue/5293-no-results-accessory-view-problems`.
2. Reinstall the pods
3. Launch the app.
4. Go to the list of posts or pages for any of your blogs.
5. Make sure you select a filter with no results.
6. In portrait mode, the ink well image should be visible at all times.
7. In landscape mode, the ink well image should not be visible ever.  Do a pull-to-refresh on the list and make sure it stays that way.
Please review @aerych 
/cc @astralbodies

Improved the code to properly hide the accessoryView in WPNoResultsView.

---

WordPress-iOS-Shared/Core/UIColor+Helpers.m
WordPress-iOS-SharedTests/UIColorHelpersTests.swift

I've updated `hexString` to support colors with only two components. This is needed for a new helper I'm adding to WPiOS which allows easier styling of attributed strings via HTML (requiring CSS / hex colors). Without this fix, `hexString` won't work with e.g. `UIColor.whiteColor()`.
To test: 
* Verify that the `UIColorHelpersTests` pass (and make sense!).
* Check the code :)
Needs review: @diegoreymendez  
Thanks!

UIColor hexString now works with grayscale colors.

---

WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/Core/WPStyleGuide.h
WordPress-iOS-Shared/Core/WPStyleGuide.m
WordPress-iOS-Shared/Core/WPTableViewCell.h
WordPress-iOS-Shared/Core/WPTableViewCell.m
WordPress-iOS-Shared/Core/WPTableViewSectionHeaderFooterView.h
WordPress-iOS-Shared/Core/WPTextFieldTableViewCell.h
WordPress-iOS-Shared/Core/WPTextFieldTableViewCell.m

Combined https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/103 and https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/104
This PR adds a toggle for disabling the layout margin hacks in `WPTableViewCell`.
We're adding a toggle here for now as to smooth the transition of WPiOS views not yet capable of coping with the loss of our long-maligned margin hacks.
In the very near future we'll remove this toggle and hack altogether when it is no longer needed.
This PR also cleans up and refactors `WPCellTextField` to follow the readable content guide.
This PR is also deprecating `WPTableViewsectionHeaderFooterview` and adding new `WPStyleGuide` configuration methods for styling the usage of default `UITableViewHeaderFooterView` instances. This brings the benefit of …

Readability, sans WPTableViewCell and WPTableViewSectionHeaderFooterView

---

WordPress-iOS-Shared/Core/WPNoResultsView.m

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/5765 by adjusting the vertical position of `WPNoResultsView` to account for table header and footer views.
To test:
* Using this branch, ensure that the no results view appears vertically centered in all locations that call `centerInSuperview` in WPiOS.
* Ensure that the no results view isn't partially hidden on the posts list on an iPhone 4s.
Needs review: @aerych

WPNoResultsView now takes into account table header and footer views

---

WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/Core/WPNoResultsView.h
WordPress-iOS-Shared/Core/WPNoResultsView.m

This PR moves the declaration for `WPNoResultsView`'s button from a private class extension to the class's header, as per the suggestion here: https://github.com/wordpress-mobile/WordPress-iOS/pull/5802#discussion_r81882366
I'm adding functionality to WPiOS which displays a popover from the button, so its frame needs to be known to provide a `sourceRect` for the popover.
Needs review: @kurzee

Expose WPNoResultsView button publicly

---

WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared-Example/WordPress-iOS-Shared-Example.xcodeproj/project.pbxproj
WordPress-iOS-Shared-Example/WordPress-iOS-Shared-Example/DeviceTableViewController.m
WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/Core/WPDeviceIdentification.h
WordPress-iOS-Shared/Core/WPDeviceIdentification.m

Our existing `WPDeviceIdentification` support for Plus sized iPhones only checks for specifically the iPhone 6 Plus (using its device name). I've added a new method to check for Plus sized phones (unzoomed), which is needed in WPiOS to customise split views slightly for these devices.
I've also added a test to the Device Identification section of the example project.
To test: 
* Open up the example project and check that the 'iPhone Plus (Any)' row shows a YES result on Plus devices. 
* Please test on a real device and on the Simulator.
* Note that the existing `isiPhoneSixPlus` method returns `YES` for any Plus device on the Simulator, but only for an actual _6+_ on devices. The new method should work for any Plus device.
* Turn on display zoom in your device's settings and check that …

Add iPhone Plus device identification

---

WordPress-iOS-Shared/Core/WPFontManager.h
WordPress-iOS-Shared/Core/WPStyleGuide.h

We need to add nullability specifiers, so that we can drop about a million `force unwraps` in the main project, plus, avoid another million unneeded casts. **Goal:** Fix all of the new compiler warnings we're getting.
**For convenience** i've made it so it's allowed to call few of the **configure** methods with nil parameters. Reasoning behind is: it's safe, (valid ObjC code), and it saves us a lot of unwrapping.
Needs Review: @astralbodies // @frosty 
(Or anyone around!).
Thanks in advance!

Nullability Specifiers

---

WordPress-iOS-Shared/Core/WPStyleGuide.h
WordPress-iOS-Shared/Core/WPStyleGuide.m

Adding dynamic type sizes to `WPStyleGuide` is a first step toward full dynamic type support.
It breaks, like, very few things :P 
Needs review: @aerych

Add dynamic type sizes to WPStyleGuide

---

README.md

This repo only gets a few issues, and they seem to be mostly ignored. I think we can track them better within the main WP-iOS repo.
Any thoughts @koke?

Redirect issues to main WP-iOS repo

---

WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/Core/WPNoResultsView.m

Updates WPNoResultsView so it looks a little bit more appealing:
1. Update button border and text color to WordPress blue
2. Update button title font to a bolder one
3. Increase view width
4. Take into account header and footer views with alpha == 0 when calculating the view position
Before        | After           
------------ | -------------

Improve no results view

---

WordPressShared/Core/Analytics/WPAnalytics.h

This adds back `WPAnalyticsStatMediaLibraryAddedPhoto` and `WPAnalyticsStatMediaLibraryAddedVideo` so that other branches of `WordPress-iOS` will still build.

Add back two missing events so develop will still build

---

WordPressShared/Core/Analytics/WPAnalytics.h
WordPressShared/Core/Analytics/WPAnalytics.m

This adds an optional `clearQueuedEvents` method to the `WPAnalyticsTracker` protocol.
I'm gonna use it to fix/cleanly implement https://github.com/wordpress-mobile/WordPress-iOS/issues/9343.

WPAnalytics: add clearQueuedEvents method

---

Podfile
Podfile.lock
WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Utility/DisplayableImageHelper.m
WordPressShared/Core/Utility/Languages.swift

This PR removes the dependency of Safe Expectation from WordPress-iOS-Shared.
Make sure all the tests are running.

Get rid of Safe-Expectations.

---

WordPressShared/Core/Views/WPNoResultsView.m

I'm working on a tweak in WPiOS where an icon is displayed in the message text of a no results view:
If `clipsToBounds` is `YES` on the message text view, the top and bottom of the icon will be clipped because they fall outside the bounds of the textView. I've disabled clipping in this PR, which I don't think should have any negative effects.
**To test:**
* Check out this PR for WPiOS, which points to this branch of WordPressShared: https://github.com/wordpress-mobile/WordPress-iOS/pull/9412
* Build and run
* Check that the icon in the no results view of Reader > Saved Posts isn't clipped
* Check that other no results views in WPiOS that have message text still look okay

WPNoResultsView: Turn off clip to bounds in message textview.

---

WordPressShared/Core/Views/WPNoResultsView.m

In https://github.com/wordpress-mobile/WordPress-iOS/pull/9412, we added a no results view for Reader Saved Posts, which includes an icon in the message text:
For users using Voiceover, this won't make complete sense when read out as-is. This PR allows us to use the no results view's `accessibilityLabel` property to provide alternative text for the no results view for Voiceover users. When an accessibility label is set, we treat the entire no results view as a single accessibility element.
**To test:**
* Check out the WPiOS branch `issue/9463-saved-posts-accessibility`.
* Navigate to Saved Posts in Reader, and ensure you have no items in there.
* Enable Voiceover, and either swipe left-to-right until the selection reaches the no results view, or otherwise tap the no results view.
* When …

Add accessibility label override to no results view

---

WordPressShared/Core/Views/WPStyleGuide+DynamicType.swift

This PR fixes a warning that was being thrown when attempting to push a new pod release:
```
-> WordPressShared (1.0.9)
- WARN  | xcodebuild:  /Users/frosty/Library/Developer/Xcode/DerivedData/App-hcdcoxdssrhlaoeunehkzekojbln/Build/Products/Release-iphonesimulator/WordPressShared/WordPressShared.framework/Headers/WordPressShared-Swift.h:446:12: warning: parameter 'for' not found in the function declaration [-Wdocumentation]
- NOTE  | xcodebuild:  /Users/frosty/Library/Developer/Xcode/DerivedData/App-hcdcoxdssrhlaoeunehkzekojbln/Build/Products/Release-iphonesimulator/WordPressShared/WordPressShared.framework/Headers/WordPressShared-Swift.h:446:12: note: did you mean 'style'?
[!] WordPressShared did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it).
``` …

Fix pod lint warnings

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Defined additional Site Creation events, as referenced in [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10208) in `WordPress-iOS`.

Added Site Creation events to Tracks

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

In reference to [PR feedback](https://github.com/wordpress-mobile/WordPress-iOS/pull/10210/) in `WordPress-iOS`, this PR defines an additional site creation event : _Site Viewed_.

Added event to track site creation success viewed

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Further addresses [#6256](https://github.com/wordpress-mobile/WordPress-iOS/issues/6256), by adding a new event `WPAnalyticsStatPushNotificationQuickActionCompleted`

Added new event to properly track notification actions

---

WordPressShared/Core/Utility/String+Helpers.swift

As discussed [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/10401), this PR exposes a new method on `String+Helpers` to count the valid text characters in a string.

Moves a character count to String extension

---

WordPressShared/Core/Utility/RichContentFormatter.swift

For context see https://github.com/wordpress-mobile/WordPress-iOS/issues/10333
Support for tables in NSAttributedStrings isn't perfect but seems good enough at this point to no longer treat tables as forbidden tags.  This PR removes the regex that would filter table tags from the passed content string.
To Test:
Run the tests, particularly `RichContentFormatterTests` and confirm tests pass.  
I'm not bumping the podspec version in this PR (yet) in case there are other changes we want to include in the next version. 
@nheagy game for a quick review?

Rich Content: Do not filter table tags from rich content.

---

WordPressShared.podspec

This fixes #167
Pointing folks to GitHub instead of apps.wordpress.com to me makes sense in the context of a `Podspec` anyways.

Use the repo URL instead of the marketing URL

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Exposes a new event associated with the tracking of Blog sharing via [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10898).

Exposed new event to track sharing a site via Reader

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Fixes [#11066](https://github.com/wordpress-mobile/WordPress-iOS/issues/11066), by exposing a new analytics event for stats chart interaction.
It may be helpful to review the [corresponding WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/11372).

Added analytics event for stats refresh chart interactions

---

WordPressShared.podspec

This PR fixes the podspec version introduced by [this](https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/197) PR.
Since **1.7.3** has been delivered, the correct version should be **1.7.4-beta.1**.

Podspec version fixed

---

WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Utility/String+URLValidation.swift
WordPressSharedTests/StringURLValidationTests.swift

Adds URL validation as an extension to String.
This PR also adds unit tests although the project isn't configured to execute those tests unfortunately.
This change was tested in a branch in `WordPressAuthenticator`.  Unfortunately, I'm not aware of a way to run the unit tests currently.
I'll look into adding support for running our unit tests in a separate PR eventually (but I need to be able to deliver this even before that's ready).
Building this should be enough to at least know it's not breaking anything.

Adds URL validation as an extension to String.

---

WordPressShared.podspec
WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Utility/Debouncer.swift
WordPressSharedTests/DebouncerTests.swift

This PR:
- Moves our `Debouncer` from WPiOS into the shared framework.
- Adds a method to be able to cancel scheduled calls.
- Adds a unit test to test the new `cancel()` method.
The reason for this move is that we need to use the `Debouncer` in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS.  The idea is to use the Debouncer to implement the error delay requested here: https://github.com/wordpress-mobile/WordPress-iOS/issues/10294#issuecomment-486260221
Important: once this is added to the shared library and a new version released, I will submit another PR to remove the Debouncer from WPiOS.
Just build and run the unit tests.
Make sure the changes look fine.

Moves WPiOS's Debouncer into WPiOS Shared.

---

WordPressShared.podspec
WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Utility/Languages.swift
WordPressShared/Core/Utility/NSBundle+WordPressShared.swift
WordPressShared/Core/Utility/WPFontManager.m
WordPressShared/Core/Views/WPStyleGuide.m
WordPressShared/Private/WPShared-Swift.h

This makes the changes needed for the WordPressShared pod to be installed as a static or dynamic framework (with or without `use_frameworks!`). Currently, it does not work correctly when installed statically.
The changes are as follows:
- Use `resource_bundles` to move resources to `WordPressShared.bundle`. This keeps the pod's resources separate from the main app.
- Replace all uses of `Bundle(for:..)`/`[NSBundle bundleForClass:]` with the new `Bundle. wordPressSharedBundle` helper.
- Use `#import "WPShared-Swift.h` instead of `#import <WordPressShared/WordPressShared-Swift.h>` to avoid the issue described in https://github.com/CocoaPods/CocoaPods/issues/7594.

Compatibility with both CocoaPods dynamic and static frameworks

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Reference: https://github.com/wordpress-mobile/WordPress-iOS/issues/11809
Changes:
- Stat `wpios_enhanced_site_creation_completed` will no longer be bumped.
- We're going back to bumping stat `wpios_site_created`.
1. Check out WPiOS branch `issue/11809-roll-back-to-bumping-site-created` (which was updated to point to the last commit in this branch).
2. Install the pods.
3. Make sure the App builds correctly.

Removes a stat that's no longer used.

---

WordPressShared.podspec
WordPressShared/Core/Views/WPStyleGuide.h
WordPressShared/Core/Views/WPStyleGuide.m

This PR removes the table view styling methods. These will now belong to the apps themselves. I believe that only WPiOS was using these because of the app-specific colors. This will make their use more clear.
See https://github.com/wordpress-mobile/WordPress-iOS/pull/11967

Remove table view styling methods

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

This PR simply adds a couple of analytics events for the new app icon switching feature in WPiOS.
```
WPAnalyticsStatAppIconChanged
WPAnalyticsStatAppIconReset
```

Add analytics events for app icon changes

---

WordPressShared/Core/Analytics/WPAnalytics.h

Ref https://github.com/wordpress-mobile/WordPress-iOS/pull/11830
Adds:
* Post list event for when the toggle button is pressed to toggle the visualization mode

Add post list toggle button event

---

WordPressShared.podspec

This is necessary because I merged #207 without bumping the version, on account of the source branch being from a third party (@leandroalonso).

Bump version number to 1.8.5-beta.1

---

WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Utility/Secret.swift
WordPressSharedTests/SecretTests.swift

I initially added this to https://github.com/wordpress-mobile/WordPressKit-iOS/pull/202 but it seems useful beyond networking, so maybe it belongs here.
`Secret` wraps a value that contains sensitive information to prevent accidental logging:
```swift
let password = Secret("my secret password")
print(password)             // Prints "--redacted--"
print(password.secretValue) // Prints "my secret password"
```

Adds Secret wrapper for sensitive information

---

WordPressShared/Core/Logging/WPSharedLogging.h
WordPressShared/Core/Logging/WPSharedLogging.m
WordPressShared/Private/WPSharedLoggingPrivate.h
WordPressShared/Private/WPSharedLoggingPrivate.m

Rather than using int as the type, we use DDLogLevel per https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/DynamicLogLevels.md.

Fix memory layout issues with DDLogLevel

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

This PR adds the key WPAnalyticsStatReaderArticleDetailReblogged for post reblogging
Feature ref. wordpress-mobile/WordPress-iOS/issues/12960
WPiOS PR: wordpress-mobile/WordPress-iOS/pull/13136

Adds tracks for post reblogging

---

WordPressShared.podspec
WordPressShared/Core/Views/WPStyleGuide+DynamicType.swift

In this PR we're fixing `WPStyleGuide.scaledFont` API, which wasn't properly returning a font with the requested weight.
**Please** verify this PR via [WordPress iOS PR 13152](https://github.com/wordpress-mobile/WordPress-iOS/pull/13152). Testing steps have been detailed there!

WPStyleGuide: ScaledFont now matches the requested weight

---

WordPressShared.podspec
WordPressShared/Core/Utility/NSDate+Helpers.swift
WordPressSharedTests/NSDateHelperTest.swift

[WPiOS PR #13265](https://github.com/wordpress-mobile/WordPress-iOS/pull/13265#issue-366111364)
Addresses an issue with display strings for posts using the device instead of site time zone: https://github.com/wordpress-mobile/WordPress-iOS/issues/13258
Some additions to `NSDate+Helpers` to adjust the display string for a date based on an optional time zone. The default formatters use the device's time zone but we want to show the site time zone in many cases.
There is some performance penalty for this: about 2x as slow as not manipulating the time zone on the formatters. I think a cache could be added at some point but I'm not sure it's worth doing right now.
Added two tests:
- `testMediumStringRelativeString`: Ensures relative formats are shown. This is not new functionality.
- …

Allow adjustment of Date display strings by Time Zone

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

[WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/13281)
Adds a `WPAnalyticsStatOpenedWebPreview` event to log when any post or page preview is opened.

Adds Web Preview analytics event

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

This adds a track for when the site used for Stats widgets changes.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13324

Adding track for widget site change.

---

WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Utility/NSString+Helpers.h
WordPressShared/Core/Utility/NSString+Helpers.m
WordPressShared/Core/Utility/NSString+Summary.swift
WordPressShared/Core/Utility/String+RemovingMatches.swift
WordPressShared/Core/Utility/String+ReplacingMatches.swift
WordPressShared/Core/Utility/String+StripGutenbergContentForExcerpt.swift
WordPressShared/Core/Utility/String+StripShortcodes.swift
WordPressSharedTests/NSStringHelpersTests.m
WordPressSharedTests/NSStringSummaryTests.swift
WordPressSharedTests/StringRemovingMatchesTests.swift
WordPressSharedTests/StringStripGutenbergContentForExcerptTests.swift

Related to https://github.com/wordpress-mobile/WordPress-iOS/issues/13154
This PR improves the existing code, adds tests, and implements logic to strip Gutenberg Galleries from excerpts.
- Migrates some of our existing code to Swift.
- Adds support for stripping Gutenberg Galleries from post excerpts.
- Adds unit tests to validate the logic.
WordPress-iOS test branch: `issue/13154-remove-gallery-captions-from-excerpts`
WordPress-Kit test branch: `issue/wpios-13154-strip-gutenberg-galleries`
Run the unit tests.
Check out the associated branches and run the unit tests.
Run the WPiOS associated branch and follow the testing steps detailed in this issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/13154
This is what you should see:

Migrates some code to Swift. Strips Gutenberg galleries from summaries.

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Adds 3 new tracks events for:
- No Site Welcome Interstitial (Post Signup Interstitial):
- Shown
- Dismiss
- Button Press
This can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13505

Adds Post Sign Up Interstitial Tracks Events

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/1883
**Related PRs:**
- `gutenberg` https://github.com/WordPress/gutenberg/pull/20317
- `gutenberg-mobile iOS and JS` https://github.com/wordpress-mobile/gutenberg-mobile/pull/1936
- `WordPress-iOS` https://github.com/wordpress-mobile/WordPress-iOS/pull/13510
- `WordPress-iOS-Shared` https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/250
- `gutenberg-mobile Android` https://github.com/wordpress-mobile/gutenberg-mobile/pull/1945
- `WordPress-Android` https://github.com/wordpress-mobile/WordPress-Android/pull/11362
---
This change adds two track events for SPT selections.  
Event: `editor_session_template_preview`
1) Open iOS app
2) Navigate to Pages
3) Create a new page
4) Select a pre-defined template
5) …

Add Session Template keys for SPT metrics on template selection

---

WordPressShared.podspec
WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Views/WPStyleGuide+SerifFonts.swift

Based on the new typography rules the system serif font will be used in place of Noto.  I've created a method to safely use New York or fallback to Noto for older iOS versions. 
Internal Ref: pbArwn-wY-p2
This can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14388

Adds a new method to use the iOS 13+ system serif (New York) font 

---

WordPressShared.podspec
WordPressShared.xcodeproj/project.pbxproj
WordPressShared/Core/Analytics/AnalyticsEvent.swift

This PR proposes a new mechanism for analytics event tracking.
There are two existing mechanisms for tracking analytics.  The older one requires that we add events to a huge list in the `WPShared` pod.  [See here](https://github.com/wordpress-mobile/WordPress-iOS-Shared/blob/a9d37616dda945514c75303a7f62db4887773aac/WordPressShared/Core/Analytics/WPAnalytics.h#L3).
The downsides are evident.  The most important one being it forced us to release a new version of the Shared pod each time an event was added, removed or changed.
The newer one was recently proposed by @leandroalonso.  It's much better than the old mechanism in that it allows us to define the events without having to release a new version of the shared pod.  [See here](https://github.com/wordpress-mobile/WordPress-iOS/blob/a48aea …

Implements a new mechanism for analytics event tracking.
