wordpress-mobile/WordPress-iOS-Shared

WordPress-iOS-Shared.podspec

Podspec version is updated to 0.1.7

---

WordPress-iOS-Shared.podspec

Podspec version is updated to 0.1.8

---

.travis.yml
Podfile
Podfile.lock
WordPress-iOS-Shared-Example/Podfile
WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared.podspec

Fix for #46
cc @astralbodies, please review

Update AFNetworking to version 2.5.1

---

WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/Core/WPFontManager.m

Update bundle usage for cocoapods 0.36

---

WordPress-iOS-Shared/Core/WPStyleGuide.h
WordPress-iOS-Shared/Core/WPStyleGuide.m

Closes #73 
Needs Review: @jleandroperez

Update tableview styles for new guidelines

---

WordPress-iOS-Shared-Example/Podfile.lock

Small update to the Podfile.lock file which was slightly outdated.
/cc @aerych

Updates the podfile.lock file.

---

WordPress-iOS-Shared/Core/WPStyleGuide.h
WordPress-iOS-Shared/Core/WPStyleGuide.m

@diegoreymendez may i bother you with a quick review?
Thanks in advance!

Adds new Alert colors

---

WordPress-iOS-Shared-Example/Podfile.lock
WordPress-iOS-Shared.podspec
WordPress-iOS-Shared/WordPress-iOS-Shared-Prefix.pch

Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/4371
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/4522
Needs Review: @diegoreymendez

Update to CocoaLumberjack 2.2.0

---

WordPress-iOS-Shared.podspec

Title has it.
/cc @aerych for review.
Once merged I'll publish the new version to Cocoapods.

Adds myself as author and changes version to 0.5.7.

---

WordPress-iOS-Shared.xcodeproj/project.pbxproj
WordPress-iOS-SharedTests/UIColorHelpersTests.swift

No release needed for this one.

Swift 3 tests migration.

---

WordPressShared/Core/Analytics/WPAnalytics.h

Adding a couple more tracks for Zendesk. (re wordpress-mobile/WordPress-iOS#9394).

Adding more tracks for Zendesk

---

WordPressShared.podspec

Bump podspec to 1.0.10

---

WordPressShared.podspec

Will merge as soon as this PR is validated.

Merges release/1.3.0 back into develop.

---

WordPressShared.podspec

Increment podspec version

---

WordPressShared.podspec

Merge release 1.7.2 into develop

Merge release 1.7.2 into develop

---

WordPressShared.podspec

Merge release 1.7.2 into master

Merge release 1.7.2 into master

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Issuer: #218  This PR adds tracking for invoking auto upload of a post

Add tracking for auto upload

---

WordPressShared.podspec

Merge release/1.8.9 into develop

Merge release/1.8.9 into develop

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Adds a new Analytics property that refers to Photos that were added from the Media Editor.

Adds Added Photo Via Media Editor

---

.circleci/config.yml

Our builds are failing on the Circle CI due to environment configuration.

Update Xcode and simulator for Circle CI

---

WordPressShared.podspec
WordPressShared/Core/Analytics/WPAnalytics.h

Needed for: https://github.com/wordpress-mobile/WordPress-iOS/pull/13021

Add WPAnalyticsStatDebugDeletedOrphanedEntities

---

WordPressShared.podspec

Merge Release/1.8.10 into develop

Merge Release/1.8.10 into develop

---

WordPressShared.podspec

Merge release/1.8.11 into develop

Merge release/1.8.11 into develop

---

WordPressShared.podspec

Merge release/1.8.12 into develop

Merge release/1.8.12 into develop

---

WordPressShared.podspec

Merge release/1.8.13 into develop

Merge release/1.8.13 into develop

---

WordPressShared.podspec

Release 1.8.13

---

WordPressShared.podspec

Merge release/1.8.14 into develop

Merge release/1.8.14 into develop

---

WordPressShared.podspec

Release 1.8.15

---

WordPressShared.podspec

Merge release 1.8.16 back into develop

Merge release 1.8.16 back into develop

---

WordPressShared.podspec
WordPressShared/Core/Analytics/AnalyticsEvent.swift

Title has it, this PR only makes two properties public for testing purposes.

Makes some properties of AnalyticsEvent public.
